### ISSUE TITLE
Investigate v3.Cluster usage

### ISSUE THREAD

**Issue by richardcase** [rancher/highlander#42]
Investigate what are the implications about using the v3.Cluster instead of the v1.Cluster.

**Comment by richardcase** [comment]
Negatives:

- The cluster doesn't appear in the new dashboard, you have to see it via the '/g'.
- The import instructions are in a different location

Positives:
- Ability to set a display name (and description)

**Comment by richardcase** [comment]
For the cluster to appear in the dashboard you need to make sure the cluster is created with a name startwith with `c-`. For example:

```yaml
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  generateName: c-
spec:
  displayName: "child1"
  description: "some cluster created by capi"
```
