### ISSUE TITLE
Investigate ephemeral GHA runners

### ISSUE THREAD

**Issue by richardcase** [rancher/highlander#45]
This is to look at how to use ephemeral GHA runners in GCP without having to put all the code into the workflow. So we should be able to do this instead:

```yaml
jobs:
  test:
    name: do-stuff
    runs-on: [self-hosted, linux]
```
